// LP Globe pipeline API client. Public publishable key; table rows require owner authentication.
const API='https://pkiliwsmcxseoczfsfar.supabase.co';
const KEY='sb_publishable_32d3KFrWN_SVr5sdEv7ekQ_1Ycwv5Qy';
const STORE='lp-globe-auth-v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE))}catch{return null}};
const write=s=>s?localStorage.setItem(STORE,JSON.stringify(s)):localStorage.removeItem(STORE);
let auth=read();
async function api(path,opts={}){let headers={'apikey':KEY,'Content-Type':'application/json',...(auth?.access_token?{'Authorization':'Bearer '+auth.access_token}:{}),...opts.headers};let res=await fetch(API+path,{...opts,headers});let body=await res.text(),data=body?JSON.parse(body):null;if(!res.ok)throw Error(data?.msg||data?.message||('HTTP '+res.status));return data}
async function refresh(){if(!auth?.refresh_token)return null;if(auth.expires_at>Date.now()/1000+90)return auth;try{let data=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:auth.refresh_token})});auth={...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in};write(auth);return auth}catch{auth=null;write(null);return null}}
window.lpAuth={async get(){await refresh();return auth},async send(email){let verifier=[...crypto.getRandomValues(new Uint8Array(32))].map(b=>'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'[b%64]).join('');sessionStorage.setItem('lp-pkce-verifier',verifier);let bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)));let challenge=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');return api('/auth/v1/otp?redirect_to='+encodeURIComponent('https://zakgedi.github.io/lp-globe/pipeline.html'),{method:'POST',body:JSON.stringify({email,create_user:true,code_challenge:challenge,code_challenge_method:'s256'})})},async accept(){let p=new URLSearchParams(location.hash.slice(1));let token=p.get('access_token');if(token){auth={access_token:token,refresh_token:p.get('refresh_token'),expires_at:Math.floor(Date.now()/1000)+Number(p.get('expires_in')||3600)};write(auth);history.replaceState(null,'',location.pathname);return auth}let code=new URLSearchParams(location.search).get('code');if(code){let verifier=sessionStorage.getItem('lp-pkce-verifier');if(!verifier)throw Error('The sign-in link must open in the same browser that requested it');let data=await api('/auth/v1/token?grant_type=pkce',{method:'POST',body:JSON.stringify({auth_code:code,code_verifier:verifier})});auth={...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in};write(auth);history.replaceState(null,'',location.pathname);return auth}return refresh()},async signOut(){try{await api('/auth/v1/logout',{method:'POST'})}catch{}auth=null;write(null)},async list(){await refresh();return api('/rest/v1/lp_pipeline?select=firm_id,stage')},async put(id,stage){await refresh();return api('/rest/v1/lp_pipeline?on_conflict=firm_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({firm_id:+id,stage})})},async del(id){await refresh();return api('/rest/v1/lp_pipeline?firm_id=eq.'+encodeURIComponent(id),{method:'DELETE'})},
async tags(){await refresh();return api('/rest/v1/lp_tags?select=id,name,color&order=name.asc')},
async cardTags(){await refresh();return api('/rest/v1/lp_card_tags?select=firm_id,tag_id')},
async createTag(name,color){await refresh();return api('/rest/v1/lp_tags',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name,color})})},
async updateTag(id,name,color){await refresh();return api('/rest/v1/lp_tags?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({name,color})})},
async deleteTag(id){await refresh();return api('/rest/v1/lp_tags?id=eq.'+encodeURIComponent(id),{method:'DELETE'})},
async setCardTag(firmId,tagId,enabled){await refresh();return enabled?api('/rest/v1/lp_card_tags',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({firm_id:+firmId,tag_id:+tagId})}):api('/rest/v1/lp_card_tags?firm_id=eq.'+encodeURIComponent(firmId)+'&tag_id=eq.'+encodeURIComponent(tagId),{method:'DELETE'})}};
