/* LP Globe roster shard C, 2026-09-29. */
(function(){if(typeof firms==="undefined"||!Array.isArray(firms))return;
const groups=[
[7,"Stanford Management Company","https://smc.stanford.edu/our-team/",[["Liam Brady","Analyst, Investment Operations"],["Phoebe Chu","Manager, Investment Operations"],["Diane Sharp","Director, Investment Operations"],["Leo Paez","Associate, Investment Operations"],["Yehbin Song","Managing Director, Operations"],["Mustafa Zohdi","Analyst, Investment Operations"]]],
[68,"Rice Management Company (Rice University)","https://investments.rice.edu/people",[["Cindy Melton","Chief Operating Officer"],["Nick Ambrose","Investment Associate"],["Scott Butterfield","Director of Real Estate Investments"],["Mina J. Kasrai","Associate Director, Performance Analytics & Reporting"],["Joshua Villegas","Portfolio Risk Manager"],["Laurence Unger","Associate Investment Director"]]],
[40,"Vanderbilt University","https://www.vanderbilt.edu/investments/about-us/",[["Bart Brunk","COO & Head of Operations"],["LeAnne Huber","Chief of Staff"],["Dorigen Lonergan","Operations Manager"],["Ryan McShane","Operations Manager"],["Cubbedge Snow","Operations Manager"],["Bill Staedeli","Operations Manager"],["Nicole Ye","Operations Manager"],["Bryce Bailey","Operations Analyst"],["Max Chmelik","Operations Analyst"],["Kathy Wirth","Operations Analyst"]]]
,[90,"University of Washington Endowment (UWINCO)","https://www.uwinco.uw.edu/team/",[["Scott Davies","Chief Operating Officer"],["Zachary Cox","Investment Operations"],["Tony Johnson","Investment Operations"],["Jennifer Kim","Investment Operations"],["Sam Senturia","Investment Operations"]]]
,[236,"Wellesley College","https://www.wellesley.edu/about-us/offices-departments/investment-office/staff",[["Julia Adelmann","Investment Operations Analyst"],["Anuja Navaratna","Chief Operating Officer"],["Cameron Pereira","Investment Operations Analyst"],["Andrea Quinn","Operations Assistant/Office Manager"]]]
,[89,"UCSF Investment Company","https://ucsfinvestco.org/ourteam.html",[["Nikita Gujral","Managing Director"],["Kaushal Shah","Chief Operating Officer"],["Jim Arnold","Director"],["Jason Kusnowo","Process Improvement Analyst"],["Nikki Ries","Senior Staff, Accounting and Operations"],["Tiffiny Gessesse","Treasury and Operations Staff"]]]
,[88,"The Ohio State University","https://busfin.osu.edu/university-business/investments/team",[["Vishnu (Vish) Srinivasan","Vice President & Chief Investment Officer"],["Samir Sidani","Managing Director"],["Timothy Reading","Senior Director of Investments"],["Renee Schlade","Director of Operations"],["Aaron Estrel","Investment Associate"],["Juliana Metz","Investment Analyst"],["Drake Sims","Senior Investment Analyst"],["Ryan Sprayberry","Investment Operations Analyst"],["Clark Nemer","Investment Analyst"]]]
,[141,"University of Toronto","https://www.utam.utoronto.ca/about-us/senior-leadership/",[["Chuck O’Reilly","President and Chief Investment Officer"],["Leon Lu","Senior Managing Director, Head of Fixed Income"],["Jean Potter","Senior Managing Director, Head of Private Markets"],["Doug Chau","Chief Risk Officer, Head of Research"],["Zohair Ahmed","Chief Operating Officer"]]]
,[229,"University of Rochester","https://www.rochester.edu/endowment/investment-staff/",[["Tammy S. Lancy","Manager of Investment Operations & Administration"],["Stephanie Westen","Manager of Investment Operations & Reporting"],["James Randall","Investment Operations Analyst"]]]
,[38,"University of Chicago","https://investments.uchicago.edu/staff-directory/",[["Michael Cameron","Manager, Business Intelligence and Performance"],["Anne Fleck","Senior Administrator, Legal and Operational Risk"],["Loryn J. Mischke","Assistant Vice President, Chief Operating Officer, and Managing Director of Operations"],["Dani Nguyen","Senior Analyst, Investment Operations"],["Emily Patel","Senior Manager of Investment Operations"],["Jason Sensat","Manager of Technology"],["Nick van Zoeren","Investments IT Administrator"]]]
,[219,"Swarthmore College","https://www.swarthmore.edu/investment-office/our-team",[["Martine Ladd","Manager, Investment Operations"]]]
,[131,"Silicon Valley Community Foundation","https://www.svcf.org/about/meet-the-team",[["Kimy Ruiz Smeraldo","Vice President, Investments"],["Lyria Zhang","Director, Investments"],["Peter Cech","Investments Coordinator"],["Tejashree Madeka","Investments Coordinator"],["Ramsey Raslan","Investments Coordinator"],["Sarah Yakubik","Investments Analyst"]]]
,[76,"Virginia Retirement System","https://www.varetire.org/about/leadership/",[["Michael Cooper","Chief Operating Officer"],["Curtis Doughtie","Chief Financial Officer"]]]
,[230,"Utah SITFO","https://sitfo.utah.gov/about-us/",[["Ryan Kulig","Finance and Operations Officer"],["Rainey Cornaby","Senior Finance and Operations Analyst"],["Tatiana Devkota","Finance and Operations Analyst"],["Ava Hamme","Finance and Operations Analyst"]]]
,[142,"Williams College","https://investment.williams.edu/team/",[["Kristin Corrigan","Office Manager & Executive Assistant"],["Emilee Ensko","Administrative Assistant"]]]
,[220,"TCU Investment Management (TCU IM)","https://endowment.tcu.edu/team/",[["Summer E. Keith","Director of Investment Operations"],["Angela H. Kenny","Senior Investment Operations Analyst"]]]
,[216,"SMU","https://www.smu.edu/investments/staff",[["David Barlow","Director of Investment Operations"],["Ruby Brist","Investment Operations Analyst"],["Mallory Burt","Executive Assistant to the Chief Investment Officer"]]]
,[140,"University of Cambridge Investment Office","https://www.ucim.co.uk/who-we-are/our-team",[["Jawad Afzali","Senior Investment Operations Analyst"],["Tom Barclay","Investment Operations Associate"]]]
,[91,"University of Wisconsin Foundation / WISIMCO","https://www.wisimco.org/team",[["Sean Arp","Chief Operating Officer of Investments"],["Dana Serwe","Investment Office Chief of Staff"],["Travis Ace","Director of Investment Operations"],["Ana Maria Murphy","Director of Investment Operations"],["Garrett Gardner","Director of Investment Operations"]]]
,[12,"State of Wisconsin Investment Board (SWIB)","https://www.swib.state.wi.us/about/board-leadership/",[["Sara Chandler","Chief of Staff & Strategy; Head of Private Markets & Funds Alpha"],["Todd Mattina","Head Economist, Asset & Risk Allocation Chief Investment Officer"]]]
,[69,"Robert Wood Johnson Foundation","https://theorg.com/org/robert-wood-johnson-foundation/teams/investment-management",[["Michael Aswad","Managing Director, Private Investments"],["Nishi Shah","Director, Public Investments"],["Warren Stock","Managing Director, Public Market Investments"]]]
,[69,"Robert Wood Johnson Foundation","https://theorg.com/org/robert-wood-johnson-foundation/teams/investment-operations-team",[["Claire Morduch","Senior Impact Investment Operations Analyst"],["Daniel Stroik","Investment Analyst, Portfolio Management"],["Justin Glover","Investment Analyst"],["Roomel Meus","Investment Analyst"],["Tina Manfre","Director, Investment Accounting, Reporting, & Tax"],["Yelin Wen","Director, Private Investments"],["Zarah Lee P. Opitz","Senior Director, Investment Operations"]]]
,[92,"W.K. Kellogg Foundation","https://www.wkkf.org/staff-team/investments/",[["Shanelle Brown","Managing Director, Public Equities"],["Shannon Comstock","Portfolio Manager, Hedge Funds and Fixed Income"],["Zachary Garcia","Investment Analyst"],["Daniel Lowry","Data and Operations Analyst"],["Leslie Orozco","Manager of Investment Operations"],["Reggie Sanders","Managing Director, Hedge Funds and Fixed Income"],["Matthew Shellenberger","Associate Director, Asset Allocation and Risk Management"]]]
,[214,"Smith College","https://www.smith.edu/your-campus/offices-services/investments",[["Corey Walker","Managing Director of Investments"],["Brian Dwyer","Director of Investment Operations"],["Caroline Thomas","Director of Investments"],["Tia Hsieh","Investment Analyst"]]]
,[272,"University of Massachusetts Foundation","https://www.umassfoundation.org/s/1355/22/foundation-home.aspx?gid=1&pgid=6787",[["DeAnna Macon","Operations and Administrative Associate, Investment Team"],["Geoffrey Bowes","Managing Director, Investment Team"],["Greg DeMatteo","Investment Analyst"],["Jon Gibbons","Chief Investment Officer"],["Derek Wade","Director of Investment Operations"]]]
,[227,"Tulane University","https://endowment.tulane.edu/investment-office-staff",[["Richard Chau","Chief Investment Officer"],["Jake Kriegsfeld","Investment Managing Director"],["Brad Bauguss","Investment Director"],["Edward Roman","Investment Associate Director"],["Zoe Haas","Investment Analyst"],["Jay Ruan","Investment Analyst"],["Paul Weaver","Director of Investment Accounting"],["Robert Lycoudes","Performance Associate"]]]
,[271,"University of Cincinnati","https://www.uc.edu/about/admin-finance/finance/investment/contact.html",[["Karl Scheer","Chief Investment Officer"],["Sam Ekis","Investment Director"],["Doreen Clark","Investment Program Director"],["Jeff Moeller","Investment Compliance & Reporting Specialist"],["Jose Cura-Zuñiga","Senior Investment Analyst"],["Claudia Muñoz-Farfan","Investment Analyst"]]]
,[275,"Wyoming Retirement System","https://retirement.wyo.gov/About/Investment-Staff/",[["Josh Keefe","Investment and Operations Risk Manager"],["Gus Mahieu","Investment Operations Coordinator"]]]
,[133,"Sofina","https://www.sofinagroup.com/the-team/our-team/",[["Harold Boël","Chief Executive Officer"],["Xavier Coirbay","Managing Director"],["Edward Koopman","Managing Director"],["Amélie Lagache","Managing Director"],["Maxence Tombeur","Managing Director"],["Ishan Ambardar","Investment Associate"],["Iason Bance","Investment Manager"],["Bhuvan Beejawat","Investment Associate"],["David Birget","Investment Manager"],["Yashvin Singh Boparai","Principal"],["Jean-François Burguet","Principal"],["Victor Casier","Managing Director"],["Caroline De Wit","Investment Associate"],["Bertrand Fawe","Principal"],["Fan Feng","Investment Associate"],["Jörg Friedl","Investment Manager"],["Alexi Gantelme","Principal"],["Vaibhav Garg","Investment Manager"],["Louise Hannecart","Investment Manager"],["Joni Iljazi","Investment Manager"],["Yana Kachurina","Principal"],["Anthony Keusters","Principal"],["Markus Kreus","Investment Manager"],["Kaylee Lawcock","Investment Manager"],["Yizhen Lim","Principal"],["Xiao-Tian Loi","Principal"],["Ainhoa Manterola Solans","Managing Director"],["Linda Mulyani","Investment Manager"],["Benjamin Sabatier","Principal"],["Tanya Sen","Principal"],["Diego Serrano","Investment Associate"],["Yanhuan Wang","Investment Manager"],["Arthur Wildiers","Investment Associate"]]]
,[265,"Sobrato","https://www.sobrato.com/our-organization/our-people/",[["Adam Dominik","Investment Director"],["Victoria Fram","Managing Director of Impact Investments"],["Abeda Iqbal","Senior Investment Associate, Impact Investment"],["Riley Sasaki","Investment Operations Manager"],["Krishna Thaker Schaff","Investment Director"],["Caroline Yarborough","Senior Investment Associate, Impact Investment"]]]
,[75,"University of Southern California","https://departmentsdirectory.usc.edu/investment-office/",[["Hailey Liu","Managing Director"],["Keaton Kitchin","Investment Associate"],["Daniel Chen","Senior Investment Analyst"],["Bob Ohanesian","Investment Operations Director"],["Cindy Chang","Investment Operations Manager, Performance Reporting and Analysis"],["Peter Hou","Investment Operations Analyst"]]]
,[270,"Trinity University","https://trinity.edu/about/strategy/endowment",[["Craig Crow","Chief Investment Officer"],["Pierre Duran","Investment Manager - Privates"],["Alison Hermann","Investment Director - Marketables"],["Michael McKinnerney","Director - Minerals and Land"],["Lynn Newman","Manager Investment Operations & Accounting"],["Felicia Velasco","Minerals Analyst"]]]
,[128,"RIT Capital Partners (Rothschild)","https://www.ritcap.com/about-us/our-people/?team=investment-manager",[["Micky Breuer-Weil","Managing Director of Investment Policy"],["Frank Ducomble","Head of Markets"],["Simon Amslinger","Investment Executive, Public Equities"]]]
,[135,"The Nature Conservancy","https://www.nature.org/en-us/about-us/who-we-are/how-we-work/finance-investing/office-of-investments/",[["Jeff Mindlin","Chief Investment Officer"],["Varun Agarwal","Associate Director, Operations and Risk"],["Seth Brotman","Chief Operating Officer / Director of Risk, Portfolio Strategy, and Operations"],["Nico Choksi","Associate Director, Investments"],["Tekola Cornetet","Investment Analyst"],["Jessica Eastling","Director of Investments"],["Zain Ijaz","Senior Investment Analyst"],["Brendan Johnson","Senior Operations Analyst"],["Molly O’Connor","Investment Manager"],["David Ruffer","Director of Investments"],["Ian Smith","Director of Investments"],["Samuel Towne","Associate Director"]]]
,[287,"The Wallace Foundation","https://wallacefoundation.org/our-team",[["Signe Conway","Managing Director, Investments"],["Sharon Ecke","Investments Office Manager"],["Nayab Gohar","Investment Accountant"],["Sophia Tsai","Chief Investment Officer"],["Joyce Zhang","Managing Director, Investments"]]]
,[268,"The Leon Levine Foundation","https://www.leonlevinefoundation.org/foundation-professionals/",[["Paige Lockhart","Investment Operations Specialist"],["M. Kelley Shepherd, Jr.","Director of Investments"]]]
,[14,"University of California Office of the President (UC Investments)","https://invest.universityofcalifornia.edu/team",[["Edmond Fong","Senior Managing Director, Absolute Return"],["Marco Merz","Managing Director, Retirement Savings"],["Margaux O’Brien","Investment Director, Public Equity"],["Byron Ong","Investment Director, Private Credit"],["John Ritter","Managing Director, Real Assets"],["David Schroeder","Managing Director, Fixed Income"],["Ronnie Swinkels","Managing Director, Public Equity"],["Matt Webster","Managing Director, Private Equity"],["Sharon Zhang","Investment Director, Private Credit"]]]
,[321,"Tiger Iron Capital","https://www.tigerironcapital.com/team",[["Matthew Schaefer","Co-founder and Managing Partner"],["Amit Tiwari","Managing Partner"],["Mary Shannon","Chief Operations Officer and Chief Compliance Officer"],["Cindy Chong","Partner"],["Kate Mitchell","Associate"]]]
,[317,"Recast Capital","https://recastcapital.com/about-us/",[["Sara Zulkosky","Co-Founder & Managing Partner"],["Ava Alemazkoor","Vice President"],["Caroline Fernandez","Director"]]]
,[8,"Temasek Holdings","https://www.temasek.com.sg/en/about-us/our-leadership",[["Dilhan Pillay Sandrasegara","Chief Executive Officer, Temasek Holdings"],["Chia Song Hwee","Chief Executive Officer, Temasek Global Investments"],["Png Chin Yee","President, Temasek Singapore and Chief Financial Officer"]]]
,[322,"VCIMCO","https://www.vcimco.com/staff",[["Michael Peltier","Chief Operating Officer"],["Lucas Hall","Vice President of Administration"],["Jacob Rexrode","Operations Associate"]]]
,[286,"Rainwater Charitable Foundation","https://rainwatercharitablefoundation.org/our-people/",[["Aaron Bigbee","Chief Investment Officer"]]]
,[269,"The Museum of Modern Art","https://www.moma.org/about/senior-staff/",[["Lou Fernandes","Chief Investment Officer"]]]
,[67,"QIC","https://www.qic.com/About-QIC/Who-we-are/Corporate-Leadership-Team",[["Allison Hill","State Chief Investment Officer"],["Ross Israel","Head of Global Infrastructure"],["Beverley Morris","Head of Liquid Markets Group"],["Deborah Coakley","Managing Director, Real Estate"],["Simon La Greca","Head of Private Debt"]]]
,[215,"Smithsonian","https://www.si.edu/about/bios/amy-chen",[["Amy Chen","Chief Investment Officer"]]]
];
for(const [id,firm,url,people] of groups){if(!firms[id]||firms[id].name!==firm)continue;
const seen=new Set(firms[id].contacts.map(c=>c.name.toLowerCase()));
for(const [name,role] of people)if(!seen.has(name.toLowerCase())){firms[id].contacts.push({name,role,notes:"Roster source: "+url+(id===69?" (third-party directory; current role unverified)":""),unverified:id===69});seen.add(name.toLowerCase())}}
})();
if(typeof renderKpis==="function")renderKpis(); if(typeof renderListRows==="function")renderListRows();
