/* H-P roster shard, sourced September 29, 2026. Secondary sources marked unverified. */
(function(){
 if(typeof firms==='undefined'||!Array.isArray(firms))return;
 const additions=[
  {id:15,name:'Jason King',role:'Investment Director',notes:'Roster source: https://theorg.com/org/university-of-notre-dame/org-chart/jason-king ; secondary directory, current status not independently confirmed by Investment Office.',unverified:true},
  {id:15,name:'Brian Wrona',role:'Investment Director',notes:'Roster source: https://theorg.com/org/university-of-notre-dame/org-chart/brian-wrona ; secondary directory, current status not independently confirmed by Investment Office.',unverified:true},
  {id:15,name:'Jacob Benedict',role:'Managing Director',notes:'Roster source: https://www.linkedin.com/in/jacob-benedict-cfa-520a8b9 ; self-described profile, current title not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Joseph Kelly',role:'Managing Director',notes:'Roster source: https://www.linkedin.com/in/joseph-kelly-cfa-31a6b2b5 ; self-described profile, current title not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Caitlin Murphy',role:'Investment Manager',notes:'Roster source: https://www.linkedin.com/in/caitlin-murphy-356852103 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Ben Grefenstette',role:'Investment Manager',notes:'Roster source: https://www.linkedin.com/in/ben-grefenstette-cfa-186888130 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Jack Freeman',role:'Investment Analyst',notes:'Roster source: https://www.linkedin.com/in/jack-freeman-a598701b9 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Hunt Hanover',role:'Chief Operating Officer',notes:'Roster source: https://www.linkedin.com/in/hunt-hanover-0466aa3 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Kelley Shrock Ramaley',role:'Senior Operations Specialist',notes:'Roster source: https://www.linkedin.com/in/kelley-shrock-ramaley-28a7a17 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Sureeni Ekanayake',role:'Director of Investment Tax Compliance',notes:'Roster source: https://www.linkedin.com/in/sureeni-ekanayake-mba-cpa-cima-81350175 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Joe Schuppig',role:'Assistant Director of Accounting and Financial Reporting',notes:'Roster source: https://www.linkedin.com/in/joe-schuppig-82165939 ; self-described profile, current status not confirmed by Investment Office.',unverified:true},
  {id:15,name:'Eric Gee',role:'Multi-Strategy Group, Investment Office',notes:'Roster source: https://www.linkedin.com/in/eric-k-gee ; self-described profile lacks an exact job title; group description only, current status unconfirmed by Investment Office.',unverified:true},
  {id:191,name:'Allison Bromley',role:'Director, Public Investments',notes:'Roster source: https://knightfoundation.org/about/staff/',unverified:false},
  {id:191,name:'Shanna Charles',role:'Director, Investment Operations',notes:'Roster source: https://knightfoundation.org/about/staff/',unverified:false},
  {id:191,name:'Julio Vasquez',role:'Investment Operations Associate',notes:'Roster source: https://knightfoundation.org/about/staff/',unverified:false},
  {id:115,name:'Diane Mulcahy',role:'Private Equity Adviser, Investments',notes:'Roster source: https://www.kauffman.org/people/diane-mulcahy/',unverified:false},
  {id:115,name:'Stephanie Deck',role:'Investment Operations Director',notes:'Roster source: https://www.kauffman.org/people/stephanie-deck/',unverified:false},
  {id:84,name:'Neamul Mohsin',role:'Chief Investment Officer',notes:'Roster source: https://www.ouem.co.uk/news/ouem-appoints-neamul-mohsin-as-cio/ ; appointment effective January 2025.',unverified:false},
  {id:84,name:'Sandra Robertson',role:'Chief Executive Officer',notes:'Roster source: https://www.ouem.co.uk/news/ouem-appoints-neamul-mohsin-as-cio/ ; announced retirement at end of 2026.',unverified:false},
  {id:64,name:'Alex Bacchus',role:'Head of Asset Allocation',notes:'Roster source: https://www.nzsuperfund.nz/about-the-guardians/management/investment-committee/',unverified:false},
  {id:116,name:'Kimberly Bakaturski',role:'Investment Records Analyst',notes:'Roster source: https://kresge.org/person/kimberly-bakaturski/',unverified:false},
  {id:116,name:'Jack Barrios',role:'Investment Associate',notes:'Roster source: https://kresge.org/person/jack-barrios/',unverified:false},
  {id:116,name:'Mo Brunner',role:'Investment Associate',notes:'Roster source: https://kresge.org/person/mo-brunner/',unverified:false},
  {id:116,name:'Elizabeth A. Goldsberry',role:'Chief Risk and Operations Officer',notes:'Roster source: https://kresge.org/person/elizabeth-a-goldsberry/',unverified:false},
  {id:116,name:'Rebecca Margavich',role:'Deal Analyst',notes:'Roster source: https://kresge.org/person/rebecca-margavich/',unverified:false},
  {id:116,name:'Kimberly Sherer',role:'Investment Operations Manager',notes:'Roster source: https://kresge.org/person/kimberly-sherer/',unverified:false},
  {id:116,name:'Victoria Shubelyak',role:'Risk & Operations Investment Analyst',notes:'Roster source: https://kresge.org/person/victoria-shubelyak/',unverified:false},
  {id:116,name:'Maximilian Zachary',role:'Investment Associate',notes:'Roster source: https://kresge.org/person/maximillian-zachary/',unverified:false},
  {id:187,name:'Andrew Lin',role:'Senior Portfolio Manager',notes:'Roster source: https://inatai.org/team/andrew-lin/',unverified:false},
  {id:187,name:'Habtamu Bekele',role:'Director of Investment Operations',notes:'Roster source: https://inatai.org/team/habtamu-bekele/',unverified:false},
  {id:187,name:'Bowei Gao',role:'Portfolio Manager',notes:'Roster source: https://inatai.org/team/bowei-gao/',unverified:false},
  {id:187,name:'Charlotte Zhang',role:'Senior Portfolio Manager',notes:'Roster source: https://inatai.org/team/charlotte-zhang/',unverified:false},
  {id:187,name:'Farid Rasuli',role:'Senior Investment Operations Analyst',notes:'Roster source: https://inatai.org/team/farid-rasuli/',unverified:false},
  {id:114,name:'Mark Wolfson',role:'Founder & Partner',notes:'Roster source: https://www.jasperridge.com/team/mark-wolfson.html',unverified:false},
  {id:114,name:'Cori Duncan',role:'CEO & Partner',notes:'Roster source: https://www.jasperridge.com/team/cori-duncan.html',unverified:false},
  {id:114,name:'Richard Hayes',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/richard-hayes.html',unverified:false},
  {id:114,name:'Cayman Seacrest',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/cayman-seacrest.html',unverified:false},
  {id:114,name:'Owen DeHoff',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/owen-dehoff.html',unverified:false},
  {id:114,name:'Aaron Abrahms',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/aaron-abrahms.html',unverified:false},
  {id:114,name:'Jenny Chen',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/jenny-chen.html',unverified:false},
  {id:114,name:'Brian Danielewicz',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/brian-danielewicz.html',unverified:false},
  {id:114,name:'Sami Mesrour',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/sami-mesrour.html',unverified:false},
  {id:114,name:'Eric Ramsay',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/eric-ramsay.html',unverified:false},
  {id:114,name:'Greg Ruiz',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/greg-ruiz.html',unverified:false},
  {id:114,name:'James Scarbrough',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/james-scarbrough.html',unverified:false},
  {id:114,name:'Nikhilesh Tandon',role:'Partner',notes:'Roster source: https://www.jasperridge.com/team/nikhilesh-tandon.html',unverified:false},
  {id:114,name:'Jeremy Klepner',role:'Managing Director',notes:'Roster source: https://www.jasperridge.com/team/jeremy-klepner.html',unverified:false},
  {id:114,name:'Tanner Lund',role:'Managing Director',notes:'Roster source: https://www.jasperridge.com/team/tanner-lund.html',unverified:false},
  {id:114,name:'Jared Mollenbeck',role:'Managing Director',notes:'Roster source: https://www.jasperridge.com/team/jared-mollenbeck.html',unverified:false},
  {id:114,name:'Rozmin Ajanee',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/rozmin-ajanee.html',unverified:false},
  {id:114,name:'Jasmine Gao',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/jasmine-gao.html',unverified:false},
  {id:114,name:'Ben Martin',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/ben-martin.html',unverified:false},
  {id:114,name:'Sarah Moyer',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/sarah-moyer.html',unverified:false},
  {id:114,name:'Jio Park',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/jio-park.html',unverified:false},
  {id:114,name:'Ari Weintraub',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/ari-weintraub.html',unverified:false},
  {id:114,name:'David Wu',role:'Principal',notes:'Roster source: https://www.jasperridge.com/team/david-wu.html',unverified:false},
  {id:114,name:'Michael Bringgold',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/michael-bringgold.html',unverified:false},
  {id:114,name:'Michael Hui',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/michael-hui.html',unverified:false},
  {id:114,name:'Molly Morales',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/molly-morales.html',unverified:false},
  {id:114,name:'Nick Rice',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/nick-rice.html',unverified:false},
  {id:114,name:'Justin Roberto',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/justin-roberto.html',unverified:false},
  {id:114,name:'Rohit Sarma',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/rohit-sarma.html',unverified:false},
  {id:114,name:'Wesley Tessier',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/wesley-tessier.html',unverified:false},
  {id:114,name:'Dan Vicas',role:'Vice President',notes:'Roster source: https://www.jasperridge.com/team/dan-vicas.html',unverified:false},
  {id:114,name:'Guillaume Diaz',role:'Associate',notes:'Roster source: https://www.jasperridge.com/team/guillaume-diaz.html',unverified:false},
  {id:114,name:'Grace Dougherty',role:'Associate',notes:'Roster source: https://www.jasperridge.com/team/grace-dougherty.html',unverified:false},
  {id:114,name:'Lillian Li',role:'Associate',notes:'Roster source: https://www.jasperridge.com/team/lillian-li.html',unverified:false},
  {id:114,name:'Jack Sanders',role:'Associate',notes:'Roster source: https://www.jasperridge.com/team/jack-sanders.html',unverified:false},
  {id:114,name:'Chloe Yoo',role:'Associate',notes:'Roster source: https://www.jasperridge.com/team/chloe-yoo.html',unverified:false},
  {id:113,name:'Hayden Millington',role:'Investments',notes:'Roster source: https://www.investure.com/hayden-millington',unverified:false},
  {id:113,name:'Jason Kang',role:'Investments',notes:'Roster source: https://www.investure.com/jason-kang',unverified:false},
  {id:193,name:'Lisa Schaefer',role:'Investment Operations Director',notes:'Roster source: https://www2.lehigh.edu/investment/team',unverified:false},
  {id:206,name:'Marla Szoradi',role:'Manager, Investment Operations',notes:'Roster source: https://www.oberlin.edu/marla-szoradi',unverified:false},
  {id:86,name:'Patricia Battaglia',role:'Director, Operations',notes:'Roster source: https://oim.psu.edu/patricia-battaglia',unverified:false},
  {id:86,name:'Gwen Dixon',role:'Senior Analyst, Operations',notes:'Roster source: https://oim.psu.edu/gwen-dixon',unverified:false},
  {id:86,name:'Jenna Doksa',role:'Senior Analyst, Operations',notes:'Roster source: https://oim.psu.edu/jenna-doksa',unverified:false},
  {id:86,name:'Karen Hammel',role:'Associate, Operations',notes:'Roster source: https://oim.psu.edu/karen-hammel',unverified:false},
  {id:86,name:'Sharon Lucas',role:'Analyst, Operations',notes:'Roster source: https://oim.psu.edu/sharon-lucas',unverified:false},
  {id:86,name:'Michael Pettit',role:'Managing Director, Operations',notes:'Roster source: https://oim.psu.edu/michael-pettit',unverified:false},
  {id:86,name:'Kathleen Schiavi',role:'Associate Director, Operations',notes:'Roster source: https://oim.psu.edu/kathleen-schiavi',unverified:false},
  {id:86,name:'Haven Smith',role:'Analyst, Operations',notes:'Roster source: https://oim.psu.edu/haven-smith',unverified:false},
  {id:86,name:'Zander Lutz',role:'Analyst, Investments',notes:'Roster source: https://oim.psu.edu/zander-lutz',unverified:false},
  {id:80,name:'Meena Lakshman',role:'Director of Investments',notes:'Roster source: https://helmsleytrust.org/our-team/',unverified:false},
  {id:80,name:'Claudia Cole',role:'Investment Officer',notes:'Roster source: https://helmsleytrust.org/our-team/',unverified:false},
  {id:80,name:'Christopher Shieh',role:'Investment Officer',notes:'Roster source: https://helmsleytrust.org/our-team/',unverified:false},
  {id:80,name:'Mike Smith',role:'Investment Officer',notes:'Roster source: https://helmsleytrust.org/our-team/',unverified:false},
  {id:80,name:'Alessandra Felloni',role:'Investment Associate',notes:'Roster source: https://helmsleytrust.org/our-team/',unverified:false},
  {id:56,name:'Thomas Kidane',role:'Co-Head of Patricia Industries',notes:'Roster source: https://www.investorab.com/about-investor/board-management/executive-leadership-team/executive-leadership-team/thomas-kidane',unverified:false},
  {id:56,name:'Daniel Nodhäll',role:'Head of Listed Companies',notes:'Roster source: https://www.investorab.com/about-investor/board-management/executive-leadership-team/executive-leadership-team/daniel-nodhaell',unverified:false},
  {id:56,name:'Yuriy Prilutskiy',role:'Co-Head of Patricia Industries',notes:'Roster source: https://www.investorab.com/about-investor/board-management/executive-leadership-team/executive-leadership-team/yuriy-prilutskiy',unverified:false},
  {id:62,name:'Michelle Knudsen',role:'Chief Investment Officer',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Adam Kobor',role:'Managing Director of Investments',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Jeff Chang',role:'Managing Director of Investments',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Ben Bronson',role:'Managing Director of Investments',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Makayla Baker',role:'Director of Investments',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Kevin Murphy',role:'Investment Analyst',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Jeff Rathgeber',role:'Managing Director of Investment Operations',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Kevin Chan',role:'Director of Investment Operations',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Tim Rojas',role:'Operations Analyst',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false},
  {id:62,name:'Caitlyn Maguire',role:'Administrative Manager',notes:'Roster source: https://www.nyu.edu/about/leadership-university-administration/organization-directory/investment-office.html',unverified:false}
 ];
 for(const {id,...c} of additions) if(firms[id]&&({15:'University of Notre Dame',191:'Knight Foundation',115:'Kauffman Foundation',84:'Oxford University Endowment Management',64:'NZ Super Fund',116:'Kresge Foundation',187:'Inatai Foundation',114:'Jasper Ridge Partners',113:'Investure',193:'Lehigh University',206:'Oberlin College',86:'Penn State (Office of Investment Management)',80:'Helmsley Trust',56:'Investor AB (Wallenberg)',62:'New York University'}[id]===firms[id].name)&&Array.isArray(firms[id].contacts)&&!firms[id].contacts.some(x=>x.name.toLowerCase()===c.name.toLowerCase())) firms[id].contacts.push(c);
})();
if(typeof renderKpis==='function')renderKpis();
if(typeof renderListRows==='function')renderListRows();
